.\" $Header: /aolnet/dev/src/CVS/sgml/docbook-to-man/cmd/docbook-to-man.sh,v 1.1.1.1 1998/11/13 21:31:59 db3l Exp $
.\"
.\"	transcript compatibility for postscript use.
.\"
.\"	synopsis:  .P! <file.ps>
.\"
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
'\" t 
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n  
.TH "cmml-validate" "1" 
.SH "NAME" 
cmml-validate \(em       validates a CMML instance document against the cmml.dtd and some further rules. 
 
.SH "SYNOPSIS" 
.PP 
\fBcmml-validate\fR [-i \fBclipid\fR  | --id \fBclipid\fR ]  [-s \fBseconds\fR  | --sec \fBseconds\fR ]  [-u \fButc\fR  | --utc \fButc\fR ]  [-b  | --verbose ]  [-h  | --help ]  [-v  | --version ] filename  
.SH "Description" 
.PP 
\fBcmml-validate\fR parses a CMML instance document 
given as \fBfilename\fR and validates it 
against the cmml.dtd returning true/false. Turn on the verbose 
option -b to print the validated CMML document to stdout. In 
case of an error the faulty tag including line and column number 
is reported. \fBcmml-validate\fR also spits out 
warnings for strange stuff. 
 
.SH "Options" 
.PP 
\fBcmml-validate\fR accepts the following options: 
 
.IP "-i \fBclipid\fR, --id \fBclipid\fR" 10 
Seek clip. Starts printing clip tags from the 
given named clip. 
.IP "-s \fBseconds\fR, --sec \fBseconds\fR" 10 
Seek seconds offset. Starts printing clip tags 
from the given time offset in \fBseconds\fR, 
e.g. 15.7.   
.IP "-u \fButc\fR, --utc \fButc\fR" 10 
Seek utc time offset. Starts printing clip 
tags from the given time offset in \fButc\fR 	time, e.g. 200301031T160000.000Z. 
.IP "-b, --verbose" 10 
Verbose mode. Writes parsed CMML document to 
stdout. 
.IP "-h, --help" 10 
Print usage message. 
.IP "-v, --version" 10 
Print version information. 
.SH "VERSION" 
.PP 
This man page is correct for CMML version 2.0 and libcmml 
version 0.8.2. 
 
.SH "SEE ALSO" 
.PP 
More information is available at: 
\fIAnnodex.net (link to URL http://www.annodex.net/) \fR      
.\" created by instant / docbook-to-man, Thu 11 Mar 2004, 13:52 
