// axAnxOggPlayer.idl : type library source for ActiveX Control project.

// This file will be processed by the MIDL compiler tool to
// produce the type library (axAnxOggPlayer.tlb) that will become a resource in
// axAnxOggPlayer.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(375E2E46-3968-41FA-99BE-35523DC57B4E), version(1.0),
  helpfile("axAnxOggPlayer.hlp"),
  helpstring("axAnxOggPlayer ActiveX Control module"),
  control ]
library axAnxOggPlayerLib
{
	importlib(STDOLE_TLB);

	//  Primary dispatch interface for CaxAnxOggPlayerCtrl

	[ uuid(B878657F-FA23-4915-8E80-6664F1738BEF),
	  helpstring("Dispatch interface for axAnxOggPlayer Control")]
	dispinterface _DaxAnxOggPlayer
	{
		properties:
		methods:

			[id(DISPID_ABOUTBOX)] void AboutBox();
	};

	//  Event dispatch interface for CaxAnxOggPlayerCtrl

	[ uuid(380DE0F9-05B8-4D01-9221-C648BC432423),
	  helpstring("Event interface for axAnxOggPlayer Control") ]
	dispinterface _DaxAnxOggPlayerEvents
	{
		properties:
			//  Event interface has no properties

		methods:
	};

	//  Class information for CaxAnxOggPlayerCtrl

	[ uuid(9B80DAA5-BCFA-44F8-B2AA-B2ECF80602A1),
	  helpstring("axAnxOggPlayer Control"), control ]
	coclass axAnxOggPlayer
	{
		[default] dispinterface _DaxAnxOggPlayer;
		[default, source] dispinterface _DaxAnxOggPlayerEvents;
	};

};
