#pragma once

template <class T>
class CProxy_IVideoTagBehaviorEvents : public IConnectionPointImpl<T, &__uuidof( _IVideoTagBehaviorEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
