.\" $Header: /aolnet/dev/src/CVS/sgml/docbook-to-man/cmd/docbook-to-man.sh,v 1.1.1.1 1998/11/13 21:31:59 db3l Exp $
.\"
.\"	transcript compatibility for postscript use.
.\"
.\"	synopsis:  .P! <file.ps>
.\"
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
'\" t 
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n  
.TH "anxenc" "1" 
.SH "NAME" 
anxenc \(em Encapsulate annotations and data into annodexed media 
 
.SH "SYNOPSIS" 
.PP 
\fBanxenc\fR [-o \fBfilename\fR  | --output \fBfilename\fR ]  [-h  | --help ] 	 [-t \fBcontent-type\fR  | --type \fBcontent-type\fR ]  	 
filename         \&...  
.SH "Description" 
.PP 
\fBanxenc\fR encapsulates annotations and data 
into annodexed media. 
 
.SH "Options" 
.PP 
\fBanxenc\fR accepts the following options: 
 
.SS "CMML generation options" 
.IP "-c, --cmml" 10 
Extract annotations as a valid CMML file (default) 
 
.IP "--head" 10 
Extract only the CMML head element 
 
.IP "-g, --granulerate" 10 
Include information about media granulerates 
 
.SS "Data track options" 
.IP "-m, --media" 10 
Extract media from annodexed media 
.SS "Miscellaneous options" 
.IP "-o \fBfilename\fR, --output \fBfilename\fR" 10 
Write output to the specified 
\fBfilename\fR instead of printing it to 
standard output. 
 
.IP "-h, --help" 10 
Display usage information and exit. 
.SH "SEE ALSO" 
.PP 
More information is available at 
\fIAnnodex.net (link to URL http://www.annodex.net/) \fR 	 
.\" created by instant / docbook-to-man, Fri 21 May 2004, 19:49 
