.\" $Header: /aolnet/dev/src/CVS/sgml/docbook-to-man/cmd/docbook-to-man.sh,v 1.1.1.1 1998/11/13 21:31:59 db3l Exp $
.\"
.\"	transcript compatibility for postscript use.
.\"
.\"	synopsis:  .P! <file.ps>
.\"
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
'\" t 
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n  
.TH "anxinfo" "1" 
.SH "NAME" 
anxinfo \(em Display information about annodexed media 
 
.SH "SYNOPSIS" 
.PP 
\fBanxinfo\fR [-v  | --verbose ]  [-h  | --help ] filename \&...  
.SH "Description" 
.PP 
\fBanxinfo\fR displays information about 
annodexed media. The default behavior is to list the \fBid\fR, \fBserial number\fR, \fBgranule rate\fR and number of \fBextra headers\fR for each track in 
\fBfilename\fR. If the \fB--verbose\fR option is given, additional information including the \fBtimebase\fR and \fBduration\fR of the file is displayed. 
.SH "Options" 
.PP 
\fBanxinfo\fR accepts the following options: 
 
.SS "Miscellaneous options" 
.IP "-v, --verbose" 10 
Display verbose information about file 
.IP "-h, --help" 10 
Display usage information and exit. 
.SH "SEE ALSO" 
.PP 
More information is available at 
\fIAnnodex.net (link to URL http://www.annodex.net/) \fR 	 
.\" created by instant / docbook-to-man, Fri 21 May 2004, 19:49 
